### ISSUE TITLE
v1.7.4 not work

### ISSUE THREAD

**Issue by Cloud0yyk** [Mara-Li/obsidian-bartender#14]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Is your feature related to a problem ?

In the latest version(1.7.4), the plugin cannot be used properly, and the button for custom sorting has disappeared.

### What solution do you want to see ?

none

### OS

Windows10

### Obsidian information

```bash session
none
```

### Plugin version

0.5.14

**Comment by Mara-Li** [comment]
Did you update Obsidian to the latest version?

**Comment by Cloud0yyk** [comment]
Yes, I have enabled the automatic update option of Obsidian, and now its version number is 1.7.4. The update log can be found in https://obsidian.md/changelog/.

**Comment by Mara-Li** [comment]
And what is the plugins version do you use? You didn't provide it in the template...

**Comment by Mara-Li** [comment]
Did you try without any other plugin and CSS disabled? Because on my side (my test vault and production) I don't have any problem…

**Comment by zihaveaDream** [comment]
I also encountered the plugin not available after upgrading to the v1.74 version, then I uninstalled the plugin and reinstalled it and now it works fine :)

**Comment by Cloud0yyk** [comment]
I tried disabling plugins and CSS styles, but Bartender still did not work.

By downloading version 0.5.18 of Bartender and replacing the corresponding files, it finally worked well.

Additionally, when I use BRAT (Beta Reviewer's Auto-update Tool) for installation or updates, an error occurs: "the release is not complete and cannot be downloaded. main.js is missing from the release."

The console shows:
```json
grabManifestJsonFromRepository response {
	"id": "obsidian-bartender",
	"name": "Bartender",
	"version": "0.5.19",
	"minAppVersion": "1.7.1",
	"description": "Allows for rearranging the elements in the status bar and sidebar ribbon",
	"author": "NothingIsLost, zansbang, Mara-Li",
	"authorUrl": "https://github.com/Mara-Li",
	"isDesktopOnly": false
}
```

**Comment by Mara-Li** [comment]
Yup, I just see the error for Bartender. Normally, it should be the 19 version that fixe the issue. I think the release was not done

**Comment by Mara-Li** [comment]
Should be resolved with the last release
