### ISSUE TITLE
[Bug]: Sort order not work properly  in 1.7.4

### ISSUE THREAD

**Issue by Lepton-Lee** [Mara-Li/obsidian-bartender#15]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

The sorting function is not working properly in 1.7.4,the plugin version is 0.5.18.
![bartender](https://github.com/user-attachments/assets/57d1f772-3e15-4f76-9a29-3338ab5d18d9)

### Minimal Reproducible Example

![bartender](https://github.com/user-attachments/assets/57d1f772-3e15-4f76-9a29-3338ab5d18d9)

### Configuration

```JSON
{
  "statusBarOrder": [],
  "ribbonBarOrder": [],
  "fileExplorerOrder": {
    "": [
      "未命名.md",
      "Adventurer",
      "define",
      "Start Here.md",
      "Vault is just a local folder.md",
      "Plugins make Obsidian special for you.md",
      "Formatting",
      "Guides"
    ]
  },
  "actionBarOrder": {},
  "autoHide": false,
  "autoHideDelay": 2000,
  "dragDelay": 200,
  "sortOrder": "custom",
  "useCollapse": true
}
```

### OS

Windows

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.7.4
	Operating system: Windows 11 Home China 10.0.22631
	Login status: logged in
	Language: zh
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 3
	Plugins enabled: 2
		1: BRAT v1.0.3
		2: Bartender v0.5.18

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

### Plugin version

0.5.18

**Comment by Mara-Li** [comment]
Read the README.MD, please. In some condition, the sort doesn't enable properly, and I didn't success to understand why. My solution, for the moment, is to lazy load after 5ms the plugin

**Comment by Mara-Li** [comment]
Will check! Maybe a chromium issue then

**Comment by Mara-Li** [comment]
Can confirm there is problem ; But it's not like it not move, but the draggable to move into a folder is enabled in the same time the moving
