### ISSUE TITLE
[FR]: Publish plugin to Obsidian's community plugins list

### ISSUE THREAD

**Issue by SublimePeace** [Mara-Li/obsidian-bartender#16]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### What solution do you want to see ?

Hi, really appreciate your work on forking and maintaining the plugin. I recommend it on reddit and to friends all the time, as it's the solution to the most requested obsidian feature of all time, custom file reordering. 

Can I ask what obstacles there are to publishing it on the community list? It would help bring more awareness to the plugin to make the Obsidian experience better for users, and it should also help bring in more contributors to maintain it.

I would especially love it because then I could recommend it to total newcomers to Obsidian, as currently I think it's way too much of a learning curve and hassle to teach them how to use BRAT to download this plugin.

I don't have experience with the [submitting process](https://docs.obsidian.md/Plugins/Releasing/Submit+your+plugin) so I want to make clear that I'm not demanding this to be done by posing it as a question, but rather to ask how I can help to make this a reality.

thank you

### Obsidian information

```bash session
-
```

### Plugin version

-

**Comment by Mara-Li** [comment]
No:
- I'm not the original maintener, and I have a huge difficulty to maintain it
- Use too much specific private API call / monkey patching.
- Don't want the noise around the publishing and the huge of new user with new bug
