### ISSUE TITLE
[Bug]: background-color not remove

### ISSUE THREAD

**Issue by ccwxl** [Mara-Li/obsidian-bartender#17]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

After sorting, the background color was not removed.

### How to reproduce ?

After sorting, the background color was not removed.

### Minimal Reproducible Example

After sorting, the background color was not removed.
![image](https://github.com/user-attachments/assets/a2432a55-5231-417c-b3a2-34c50daeae2f)

### Configuration

```JSON
{
  "statusBarOrder": [],
  "ribbonBarOrder": [],
  "fileExplorerOrder": {
    "": [
      "yrnet",
      "MHAuto",
      "NVR",
      "工作",
      "架构",
      "微服务",
      "运维",
      "Java",
      "Database",
      "Rust",
      "Golang",
      "Kubernetes",
      "README.md"
    ]
  },
  "actionBarOrder": {},
  "autoHide": false,
  "autoHideDelay": 2000,
  "dragDelay": 200,
  "sortOrder": "custom",
  "useCollapse": true
}
```

### Relevant log output

```bash session
After sorting, the background color was not removed.
```

### Anything else?

After sorting, the background color was not removed.

### OS

Windows

### Obsidian information

```bash session
1.7.6
```

### Plugin version

latest

**Comment by Mara-Li** [comment]
Did you update to the last chromium version? Updating using re-installing obsidian by the executable
