### ISSUE TITLE
[Bug]: After dragging ribbon items for order re-arrangement, the collapse button disappears.

### ISSUE THREAD

**Issue by XMB-7** [Mara-Li/obsidian-bartender#2]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

Current state: 
![image](https://github.com/Mara-Li/obsidian-bartender/assets/65625632/f5c14fc9-471f-4c02-8bfb-d4dbe09210f4)

---

Drag ribbon items for order re-arrangement would make the collapse button disappear. 
![recording](https://github.com/Mara-Li/obsidian-bartender/assets/65625632/a90eab23-5994-47b9-b647-ab823586b5a4)

---

Re-enable the plugin would bring the collapse button back, but would also lose the customized order, which the play button should be at the bottom.
![recording](https://github.com/Mara-Li/obsidian-bartender/assets/65625632/56dcde80-b078-4794-9b7d-dde3672e6806)

**Comment by Mara-Li** [comment]
See my comments on #1 
The plugin shouldn't be disabled without reloading Obsidian.
