### ISSUE TITLE
[Bug]: Fail to launch obsidian

### ISSUE THREAD

**Issue by XMB-7** [Mara-Li/obsidian-bartender#7]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

Severe bug for the new version. Only by disabling this plugin can Obsidian start normally, even for the native sandbox vault.

![image](https://github.com/user-attachments/assets/ba75b2c1-57ea-4d71-addd-502fefa99c10)

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.5
	Operating system: Windows 11 Home China 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: BRAT v1.0.2
		2: Bartender v0.5.16
```

**Comment by Kami958** [comment]
I encountered the same issue. Hope it can be fixed.

**Comment by Deathwing1999** [comment]
Me Too

**Comment by raging-flames** [comment]
我也遇到了，经过排查是这个插件引起的

**Comment by wangyidong666** [comment]
ME oo too

**Comment by wangyidong666** [comment]
Me too too，Hope fix it quickly.

**Comment by Mara-Li** [comment]
Also:
- Please follow template for signaling bug
- I don't reply to message in Chinese. Unlike the first maintainer, I'm not Chinese (French here 👋 )
