### ISSUE TITLE
[Bug]: Regression - filter not working MacOS

### ISSUE THREAD

**Issue by RobOK2050** [Mara-Li/obsidian-bartender#9]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

I updated to the .16 release (THANK YOU FOR UPDATING THIS PLUGIN!!!) and the filter stopped working. No matter what I type in, no changes happen to the file list. Since one of the fixes was the Excluded Files, I removed all of my excluded folders (archive folders) but that did not fix it. Let me know if you want me to try anything else to debug. 

### Minimal Reproducible Example

Filtering has no effect

### Configuration

```JSON
{
  "statusBarOrder": [],
  "ribbonBarOrder": [
    "46153890361507843217128156",
    "79197221253283843554360994",
    "22537797936087042100426429",
    "76917925058969602487345714",
    "24931855656550401188934136",
    "70539640926371843199063707",
    "22125266327306241085394312",
    "62086243344711681235738650",
    "3856008753446912907088109"
  ],
  "fileExplorerOrder": {},
  "actionBarOrder": {},
  "autoHide": true,
  "autoHideDelay": 2000,
  "dragDelay": 200,
  "sortOrder": "byModifiedTime",
  "useCollapse": true
}
```

### OS

MacOS

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.7.1
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 24.0.0: Mon Aug 12 21:29:00 PDT 2024; root:xnu-11215.1.10~5/RELEASE_ARM64_T6000 24.0.0
	Login status: logged in
	Language: en
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.7.18
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 38
	Plugins enabled: 29
		1: Hotkeys++ v0.2.7
		2: Minimal Theme Settings v8.1.1
		3: Smart Random Note v0.2.1
		4: Better Word Count v0.10.1
		5: Hotkey Helper v0.3.18
		6: Note Refactor v1.8.2
		7: BRAT v1.0.2
		8: Dynamic Table of Contents v0.0.27
		9: Outliner v4.8.1
		10: Calendar v1.5.10
		11: Plugin Update Tracker v1.5.2
		12: Settings Search v1.3.10
		13: Recent Files v1.5.0
		14: Dataview v0.5.67
		15: Style Settings v1.0.9
		16: Tag Wrangler v0.6.1
		17: Commander v0.5.1
		18: Homepage v4.0.4
		19: Periodic Notes v0.0.17
		20: Legacy vault switcher v1.0.0
		21: Focus Mode v1.11.4
		22: File Explorer Note Count v1.2.2
		23: Paste URL into selection v1.7.0
		24: Auto Note Mover v1.2.0
		25: Broken Links v1.2.2
		26: Find orphaned files and broken links v1.10.1
		27: Advanced Tables v0.22.0
		28: Snippet Downloader v2.0.1
		29: Bartender v0.5.16
```

### Plugin version

Bartender v0.5.16

**Comment by Mara-Li** [comment]
Hmm, strange it doesn't work on macOs. It works on my iphone and my windows...

**Comment by Mara-Li** [comment]
Edit : I noticed some bug on IOS (no typing result and it unlock the moving)

**Comment by Mara-Li** [comment]
Edit 3 : Okay, repro on windows

**Comment by Mara-Li** [comment]
I released a fix in beta release, it is possible for you to test it?

**Comment by mzhhzm** [comment]
> I released a fix in beta release, it is possible for you to test it?

Yes, it's now working fine on my Android mobile. Thank you very much!

**Comment by RobOK2050** [comment]
> I released a fix in beta release, it is possible for you to test it?

Confirmed working here too! Yay!

**Comment by Mara-Li** [comment]
Noticed that the way I fix it disabled (again) the custom sort.
Now, everything should work.

last beta is based on refactor branch.
